### ISSUE TITLE
Launch/Debug error: 

### ISSUE THREAD

**Issue by Theblackdove** [overturetool/vdm-vscode#196] opened 2022-11-21 15:58 UTC
Hi guys..... 
I'm working on a mini project as a part of the Modelling of Critical Systems on the University of Aarhus. Until now I haven't had problems with the vdm extension in VS Code. I've been able to launch/debug without issues. But today I got the following error message in the output terminal (se below).

Earlier today I installed the puml extension with recommended requirements for visualizing the auto-generated class diagram, but the launch/debug functionality still worked the next couple of hours, so I don't know if that could be the reason? 

I've tried to re-install VS Code without success. 

I hope you can help me on this issue? :-) 

*project source can be found here https://github.com/Theblackdove/MCS_project.git
*(Both _main_ and _new_flow_ branches should be able to launch without issues)

ERROR_MESSAGE:
"
Exception in thread "DAP Listener" java.lang.IncompatibleClassChangeError: class com.fujitsu.vdmj.scheduler.SchedulableThread overrides final method java.lang.Thread.isVirtual()Z

at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at dap.handlers.ThreadsHandler.run(ThreadsHandler.java:70)
	at dap.DAPDispatcher.dispatch(DAPDispatcher.java:69)
	at dap.DAPServer.run(DAPServer.java:122)
	at dap.DAPServerSocket.run(DAPServerSocket.java:97)
	at java.base/java.lang.Thread.run(Thread.java:1589)
"

**Comment by nickbattle** [comment] 2022-11-21 16:10
This is caused by the latest version of Java, version 19. They've introduced a new final `isVirtual()` method on Thread, but that method already exists in `SchedulableThread`.

So the quickest way forward is to use an earlier version of Java, if you can.

VDMJ is already fixed, but this is still in SNAPSHOT. I can let you have a jar to update the extension (easy), or you can wait till the next 1.3.7 release (which we may be able to bring forward, if lots of people are seeing this).

**Comment by Theblackdove** [comment] 2022-11-21 16:47
Thank you so much Nick, for the quick answer..... It's up and running again!!! With the quickest solution proposed :-)

**Comment by leouk** [comment] 2022-11-23 17:04
On a student laptop, he got this error when trying to launch/debug "Cannot read properties of undefined (reading 'uri')". There was no log, and when trying to add one, none was created. Any clues/hints to what's causing this? He reinstalled and things seemed to go back to working normal.

**Comment by nickbattle** [comment] 2022-11-23 17:17
I think your issue is the same as #185, @leouk . This #196 is different.

**Comment by idhugoid** [comment] 2022-11-25 10:44
Fixed by new jars...

**Closed as completed by idhugoid** 2022-11-25 10:44 UTC
