### ISSUE TITLE
script command

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#156] opened 2022-05-10 15:36 UTC
Nick, is the script command available in VSCode? 

I couldn’t get it to work (if it is). Being such a useful/important one for larger models,  I wondered if it would be too much to add that?

**Comment by nickbattle** [comment] 2022-05-10 16:13
It isn't provided as it stands. I think I looked at this when you asked me before, and it isn't trivial to create, but I can look again.

The problem will be because, as far as the Client is concerned, you are executing one thing (say, `script myscript`), but that script may expand to have multiple executions, which will send multiple completions back to the Client. It may be possible to catch intermediate results and swallow them somehow though.

I'll take another look. I do see how this would be useful.

**Comment by nickbattle** [comment] 2022-05-10 16:25
Another problem is that evaluations (`print <exp>`) are evaluated asynchronously in VSCode, so that the Client can interrupt them. That means that the script cannot simply execute commands in sequence, but it has to work out what is already running and wait for that to complete before doing the next step. Not impossible, but harder than the command line...

**Comment by leouk** [comment] 2022-05-10 16:56
I see. Hum...

 the use case is not about printing state or other "results" (Ie run traces or coverage done), but rather get to the "right" point for debugging 

So how about a "simpler"Command than script (Ie full interpreter Fms's) on VSCode? 

Think like calling a vdm "program"
On the fly? (Ie the script is like a Main() == (script...); op?

That is the script can only contain either function composition or operation sequential composition? Or some text that would "parse" as either a function or operation? 

This way, with wrapping, the "call" (for script in VSCode) command would just call it and get the state to place of interest? 

Would that work / be simpler?

**Comment by nickbattle** [comment] 2022-05-10 17:36
Yes, the problem is that the async print commands are sending back a completion message which the Client is thinking is the end of the "script" evaluation. So when it then gets another one from the next print command, it's confused.

Can you show me an example script of the things that you want to do?

**Comment by leouk** [comment] 2022-05-10 17:47
I see. Something like

Test.script=
  p Op1(10)
  p St
  p Op2()

Test.call= 
  Op1(10);
  Op2();

Of course it's the user's job to write both abs VSCode can only cope with the second. 

If execution breaks during the chain that's fine. If it reaches the end, I am the sweet spot I wanted?

**Comment by nickbattle** [comment] 2022-05-11 09:18
I've just pushed something to the "development" branch (in LSP) to support this. The limitation I had to impose is that you can't interrupt or debug the evaluations for now. I think I can make them debuggable, but making them interruptable would be very difficult. Hopefully this is still useful though?

Can you give it a try?

```
script test.script
print f(1)
= 2
print g(1)
= 0
print op(123)
= ()
p s1
= 123
init
= ()
Global context initialized
Cleared all coverage information
p s1
= undefined
END test.script
```

**Comment by leouk** [comment] 2022-05-11 09:20
Or even (perhaps more involved) to add @Printf for corresponding p which is an expression? 

Test.script=
p x
p f(x)
p Op1(10)
p St
p Op2()
p St

Test.call = 
--@Printf("p x = %1$s", x)
--@Printf("p f(x) = %1$s", f(x))
Op(10);
--@Printf("p St = %1$s", St)
Op2();
--@Printf("p St = %1$s", St)
skip;

I presume that Test.call is the wrapped in something like DEBUG: () ==> () that gets called by the interpreter as "p DEBUG()"

**Comment by nickbattle** [comment] 2022-05-11 09:29
Yes, you'll need to pull, "mvn clean install" from development and then setlinks.sh.

Note that they've just released a 1.3.3 version, which might be worth picking up too, before the setlinks.

Note also that they've changed the name of the extension to "overturetool", so setlinks needs to be tweaked. I'll attach mine FYI...

[setlinks.sh.txt](https://github.com/overturetool/vdm-vscode/files/8668576/setlinks.sh.txt)

**Comment by nickbattle** [comment] 2022-05-11 11:34
Hmm... I've tried to make scripts debuggable, but the obvious change doesn't work. As far as I can see, the Client is being sent the right messages at the breakpoint, but the UI does not respond as though it has hit a break (though it does sometimes displays "stopped at breakpoint"). It's strange, and may be a Client side bug, though it's more likely that scripts are upsetting it somehow - though the message exchanges do seem identical to a regular debug session.

I've checked in the change but commented out, so it works as before for now. I'll take another look when I get time.

**Comment by nickbattle** [comment] 2022-05-11 15:26
Right, I understand why it's hard to make scripts debuggable!  The reason is that the script is executed on the main DAP thread, spawning worker threads as necessary to execute the individual steps. That's fine, but when you stop at a breakpoint the DAP thread has to start listening for more (debug related) chatter from the Client. So we would have to make script steps asynchronous in some way, letting the DAP thread listen in between steps. But then you have difficulty resuming the script - how and when do you do this?

It would presumably be possible to coordinate async steps with async executions and DAP debugging messages, but it's quite fiddly. I'll have a think about it, but for now we'll have to say that scripts are just "run this" steps without any sophistication.

**Comment by nickbattle** [comment] 2022-05-11 20:51
OK... I had to fix this, or else it would bug me all the time :-)  So now there is an asynchronous script executor which allows scripts to be interrupted and debugged. It should look the same, except it will now stop at breakpoints and so on. Note that if you attempt to abort an execution (say at a break) or an evaluation throws some runtime VDM error, it will try to carry on to the next item in the script, which may not be ideal(?)

As before, can you give this a try Leo - it's in "development" as usual?

**Comment by nickbattle** [comment] 2022-05-20 10:43
*cough* @leouk, does it work? :)

**Comment by leouk** [comment] 2022-05-21 06:59
Yep :-). Sorry forgot to mention.

**Comment by nickbattle** [comment] 2022-05-21 10:19
Great, thanks. Will close.

**Closed by nickbattle** 2022-05-21 10:19 UTC
Labels: enhancement, fixed in VDMJ
