### ISSUE TITLE
hovering watch inconsistency?

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#168] opened 2022-05-20 07:13 UTC
If you "hover" over a variable during a debugging session, you get an "on-the-fly" watch for that variable, which is quite useful. I then noticed a situation where the value is not consistent with respect to a corresponding defined watch. 

let 
   x = f(..), 
   x' = if x > y then x else y
in
   x' < y

If you hover over the value of x' you get the value of x instead! This seems to be specifically for such decorated variables.

**Comment by nickbattle** [comment] 2022-05-20 07:24
Would it be possible to get a log extract for when this happens?

**Comment by leouk** [comment] 2022-05-20 09:34
To reproduce: 
default HoveredWatchCapture
p f(10) 

presuming a breakpoint set at line 11; if you hover over y or y' you see 11, instead of 11 and 21 as the "real" watch shows.

Example file:
[HoveredWatchCapture.vdmsl.zip](https://github.com/overturetool/vdm-vscode/files/8738242/HoveredWatchCapture.vdmsl.zip)

Log from example file:
[VSCode_lang_server.log](https://github.com/overturetool/vdm-vscode/files/8738239/VSCode_lang_server.log)

**Comment by nickbattle** [comment] 2022-05-20 09:45
OK, thanks for those. I can reproduce the problem. But this seems to be something that the client does - it looks like it figures out the hovered variable name by some text-based rule and then shows that variable in the hover. But the rules don't understand the use of a "prime" apostrophe. There are no extra messages sent to the server when you hover (maybe a codeLens refresh, but that's all I can see).

@FrederikPM do you know whether this hover text rule can be influenced at the client.

**Comment by leouk** [comment] 2022-05-20 09:55
Of course this is "trivial" to get around (just give y' another name). 

Guess the real issue is the confusion it creates (took a while to figure out what was going on). 

Made me wonder whether there are other such naming rules that it gets confused. That's more the issue I think.

**Comment by nickbattle** [comment] 2022-05-20 10:42
Well, the debugger is reporting incorrect results, so that's quite important to fix!

The other naming context I can think of is when you click on a symbol and F12 or Shift-F12 to get its definition/references. But in that case the Server is involved. I "hunt" through the AST looking for the location that corresponds to the cursor, and lookup that name. So I know the naming rules and it all works. In your case, the UI is applying a text-rule to extract the name in the hover and then looking that up in the top stack frame (that's a guess... but it seems right).

Good spot.

**Comment by nickbattle** [comment] 2022-05-20 10:47
I just checked F12/Shift-F12 with the `y'` and that fails(!!). So I'll try to fix that too, but it isn't linked to the hover issue.

**Comment by nickbattle** [comment] 2022-05-20 12:15
OK, that was a small error, now fixed in development.

Related to the hover, when you click on a name in the editor, you get a lightweight "show occurrences" where every copy of the same name is highlighted, regardless of whether it is the same definition (ie. it's just textual). But this also does not understand the "prime", so it highlights all occurrences of `y` and `y'`. Presumably this is using the same name-extract method, which does not include aprostrophes or (I just tried) dollar signs, which are also legal VDM.

**Comment by FrederikPM** [comment] 2022-05-24 07:50
Hi Nick,
I'm still looking into this. But for now it seems like there is at least one way to fix this issue which would be for the debug adapter to announce "supportsEvaluateForHovers: true" as part of its capabilities response. Then, as I understand it, VSCode will not use its native logic to resolve the hovered over value but will always pass the hovered over value to the adapter to be evaluated. However, I'm not sure how much extra work this would be on the server side?
Alternatively I might yet discover some alternative solution where we could influence the native logic of VSCode.

**Comment by nickbattle** [comment] 2022-05-24 11:08
OK, that may be a way forward, though as you say it is adding a burden to the server. Let's try to find a client side solution. If it can't be done, I'll enable this feature and see what information it needs. I wouldn't want to lose useful "default" hovers though. Do you know what hover features the client provides (assuming these would need to be provided by the server)?

**Comment by FrederikPM** [comment] 2022-05-24 12:43
I found a solution whit registering a evaluatable expression provider on the client side.
I'm then able to define, with a regex, which combination of characters constitutes an evaluatable expression, e.g.: y' and not only y.
The provider will be triggered every time the user hovers anywhere in the spec during debugging.
So now I just need to know which special characters and which combination with letters are allowed in VDM and if it differs between the dialects. Is this documented somewhere or do you know it?

**Comment by leouk** [comment] 2022-05-24 12:56
I had to figure out the code for valid VDM identifiers and is quite complex! but then VDMJ has a method for it somewhere in LexTokenReader tree I think? Can't quite remember. Effectively, it's a function from string to boolean saying whether the name is a valid one for VDM or not :-). @nickbattle do you remember where that is?

**Comment by nickbattle** [comment] 2022-05-24 13:20
Sorry, I sent the previous answer on the phone and didn't realise what you'd asked!

There are two methods in LexTokenReader: startOfName and restOfName. They both take a character and return whether it's valid for a start or the rest of a variable name - some characters aren't legal at the start. Note that it also includes various broad Unicode character classes. This is so that we can deal with (say) Japanese and so on. Hopefully something similar is available in Typescript (since this is all Unicode based, I think)?

**Comment by leouk** [comment] 2022-05-24 13:26
That's right, those are the ones. I took them and "combined"/simplified in vdm_toolkit, but yes, to take into account various funny unicode characters allowed by the ref manual lexer appendix! @FrederikPM it's nice to have found a solution in the client as well, as this will "age" better I think.

**Comment by FrederikPM** [comment] 2022-05-25 07:21
Hi guys.
I have implemented a possible fix to the issue. Under the presumption that VDMJ already validates the variable names, the regex pattern that defines what constitutes an evaluatable expression is rather loose and there is no validation in the evaluatable expression provider. This seems to work as I would guess that the native hovering logic takes the evaluatable expression and evaluates it in the context of the debug session and maybe also with some knowledge of the grammar. So although part of a control statement would also be passed as an evaluatable expression it has no effect.
I have tested it with Leos example where I also substituted the variable names with some Japanese which also worked. There is a VSIX available [here](https://github.com/overturetool/vdm-vscode/actions/runs/2379304936). Can you try it out if you can find the time? :)

**Comment by nickbattle** [comment] 2022-05-25 07:32
Sounds good!  We're about to take a short break, but I can look at this at the weekend.

**Comment by FrederikPM** [comment] 2022-06-20 06:37
Hi @nickbattle 
Have you had the time to take a quick look at this yet?

**Comment by nickbattle** [comment] 2022-06-20 07:40
I'm on holiday at the moment, until next Monday  :-(

**Closed** 2022-06-23 11:59 UTC
Labels: bug
